// Settings
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRECING = 'SET_IS_REFRECING';
export const SET_IS_LOADING_MORE = 'SET_IS_LOADING_MORE';
export const GET_SPLASH = 'GET_SPLASH';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_TAB_VISIBLE = 'SET_TAB_VISIBLE';
export const GET_HOME_DATA = 'GET_HOME_DATA'
export const SET_HOME_SIMMER_VISIBLE = 'SET_HOME_SIMMER_VISIBLE'

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_FACEBOOK_LOGIN = 'ON_FACEBOOK_LOGIN'
export const ON_GOOGLE_LOGIN = 'ON_GOOGLE_LOGIN'
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION'
export const ON_CUSTOMER_REGISTRATION = 'ON_CUSTOMER_REGISTRATION'

//Payments
export const ON_WALLET_RECHARGE = 'ON_WALLET_RECHARGE'
export const LIVE_COURSE_PAYMENT = "LIVE_COURSE_PAYMENT"
export const GET_WALLET_RECHARGE_PLANS = "GET_WALLET_RECHARGE_PLANS"
export const SET_WALLET_RECHARGE_PLANS = "SET_WALLET_RECHARGE_PLANS"

//Customer
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';
export const SET_BLOGS = 'SET_BLOGS';
export const SET_TESTIMONIALS = 'SET_TESTIMONIALS';

//Astrologer
export const GET_CHAT_CALL_ASTROLOGER_LIST = 'GET_CHAT_CALL_ASTROLOGER_LIST';
export const SET_CHAT_ASTROLOGER_LIST = 'SET_CHAT_ASTROLOGER_LIST';
export const SET_CALL_ASTROLOGER_LIST = 'SET_CALL_ASTROLOGER_LIST';
export const GET_ASTROLOGER_DETAILS = 'GET_ASTROLOGER_DETAILS';
export const SET_ASTROLOGER_DETAILS = 'SET_ASTROLOGER_DETAILS';
export const GET_ASTROLOGER_REVIEWS = 'GET_ASTROLOGER_REVIEWS'
export const SET_ASTROLOGER_REVIEWS = 'SET_ASTROLOGER_REVIEWS';
export const SET_CHAT_REQUEST_MODAL_DATA = 'SET_CHAT_REQUEST_MODAL_DATA';
export const SET_ASTROLOGER_RATING_DATA = 'SET_ASTROLOGER_RATING_DATA';
export const SET_WALLET_ALERT_VISIBLE = 'SET_WALLET_ALERT_VISIBLE';
export const ON_ASTROLOGER_RATING = 'ON_ASTROLOGER_RATING';
export const SET_RECENT_ASTROLOGERS = 'SET_RECENT_ASTROLOGERS';
export const SET_ONLINE_ASTROLOGERS = 'SET_ONLINE_ASTROLOGERS';
export const SET_OFFER_ASTROLOGERS = 'SET_OFFER_ASTROLOGERS';
export const SET_TRENDING_ASTROLOGERS = 'SET_TRENDING_ASTROLOGERS'
export const ON_FOLLOW_UNFOLLOW_ASTROLOGERS = 'ON_FOLLOW_UNFOLLOW_ASTROLOGERS';
export const CHECK_FOLLOW_STATUS = 'CHECK_FOLLOW_STATUS';
export const SET_FOLLOW_STATUS = 'SET_FOLLOW_STATUS';
export const SET_ASTROLOGER_FILTERS_VISIBLE = 'SET_ASTROLOGER_FILTERS_VISIBLE'
export const SET_ASTROLOGER_FILTERS = 'SET_ASTROLOGER_FILTERS'
export const CLEAR_ASTROLOGER_FILTERS = 'CLEAR_ASTROLOGER_FILTERS'
export const SET_ASTROLOGER_SKILLS = 'SET_ASTROLOGER_SKILLS'
export const SET_ASTROLOGER_REMEDIES = 'SET_ASTROLOGER_REMEDIES'
export const SET_ACTIVE_REMEDIES = 'SET_ACTIVE_REMEDIES'
export const SET_ASTROLOGER_OFFERS = 'SET_ASTROLOGER_OFFERS'
export const ON_ASTROLOGER_SEARCH = 'ON_ASTROLOGER_SEARCH'
export const SET_ASTROLOGER_SEARCHED_DATA = 'SET_ASTROLOGER_SEARCHED_DATA'
export const SET_ASTROLOGER_SEARCH_TEXT = 'ASTROLOGER_SEARCH_TEXT'


//Call
export const SEND_CALL_REQUEST = 'SEND_CALL_REQUEST';
export const GET_CALL_INVOICE_DATA = 'GET_CALL_INVOICE_DATA';
export const SET_CALL_INVOICE_DATA = 'SET_CALL_INVOICE_DATA';
export const SET_CALL_BANNER_DATA = 'SET_CALL_BANNER_DATA';

//product
export const GET_CATEGORY_WAISE_PRODUCT_DATA = "GET_CATEGORY_WAISE_PRODUCT_DATA"
export const GET_PRODUCT_CATEGORY_DATA = "GET_PRODUCT_CATEGORY_DATA"
export const GET_PRODUCT_DETAILS_BANNER = "GET_PRODUCT_DETAILS_BANNER"
export const GET_PRODUCT_CATEGORY_BANNER = "GET_PRODUCT_CATEGORY_BANNER"
export const PRODUCT_PAYMENT = "PRODUCT_PAYMENT"
export const PRODUCT_CUSTOMER_ADD_ADDRESS = "PRODUCT_CUSTOMER_ADD_ADDRESS"


//cart
export const ADD_TO_CART = "ADD_TO_CART"
export const GET_CART_DETAILS = "GET_CART_DETAILS"

// pooja
export const GET_CATEGORY_WAISE_POOJA_DATA = "GET_CATEGORY_WAISE_POOJA_DATA"
export const GET_POOJA_CATEGORY_DATA = "GET_POOJA_CATEGORY_DATA"
export const GET_POOJA_DETAILS_BANNER = "GET_POOJA_DETAILS_BANNER"
export const GET_POOJA_CATEGORY_BANNER = "GET_POOJA_CATEGORY_BANNER"

//course
export const GET_COURSE_BANNER = "GET_COURSE_BANNER"
export const GET_COURSES_LIST = "GET_COURSES_LIST"
export const GET_LIVE_CLASS = "GET_LIVE_CLASS"
export const GET_DEMO_CLASS = "GET_DEMO_CLASS"
export const GET_WORKSHOP = "GET_WORKSHOP"
export const GET_WORKSHOP_WITHOUT_ID = "GET_WORKSHOP_WITHOUT_ID"
export const GET_TEACHERS_LIST = "GET_TEACHERS_LIST"
export const BOOKED_DEMO_CLASS = "BOOKED_DEMO_CLASS"
export const LIVE_CLASS_OF_CLASS = "LIVE_CLASS_OF_CLASS"
export const CHECK_CUSTOMER_DEMO_CLASS_BOOKED = "CHECK_CUSTOMER_DEMO_CLASS_BOOKED"
export const GET_ALL_DEMO_CLASSS = "GET_ALL_DEMO_CLASSS"
export const REGISTER_FOR_LIVE_CLASS = "REGISTER_FOR_LIVE_CLASS"
export const IS_REGISTER_FOR_LIVE_CLASS = "IS_REGISTER_FOR_LIVE_CLASS"
export const GET_SINGLE_DEMO_CLASS = "GET_SINGLE_DEMO_CLASS"
export const GET_SINGLE_LIVE_CLASS = "GET_SINGLE_LIVE_CLASS"
export const GET_REGISTERED_LIVE_CLASS = "GET_REGISTERED_LIVE_CLASS"
export const GET_CURRENT_LIVE_COURSE_HISTORY = "GET_CURRENT_LIVE_COURSE_HISTORY"
export const GET_COMPLETED_LIVE_COURSE_HISTORY = "GET_COMPLETED_LIVE_COURSE_HISTORY"
export const GET_COURSE_HISTORY = "GET_COURSE_HISTORY"

//mcq
export const GET_MCQ = "GET_MCQ"
export const SUBMIT_MCQ = "SUBMIT_MCQ"
export const SUCCESS_MCQ = "SUCCESS_MCQ"
export const ATTEMPTED_MCQ_TIMES = "ATTEMPTED_MCQ_TIMES"

//Chat
export const SET_CHAT_BANNER_DATA = "SET_CHAT_BANNER_DATA"
export const SEND_CHAT_REQUEST = 'SEND_CHAT_REQUEST';
export const START_CHAT = 'START_CHAT';
export const SET_CHAT_DATA = 'SET_CHAT_DATA';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES'
export const SET_CHAT_TIMER_COUNTDOWN = 'SET_CHAT_TIMER_COUNTDOWN'
export const SET_CHAT_REQUESTED_DATA = 'SET_CHAT_REQUESTED_DATA'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE'
export const ON_END_CHAT = 'ON_END_CHAT'
export const ON_CLOSE_CHAT = 'ON_CLOSE_CHAT'
export const ON_CHAT_IMAGE_SEND = 'ON_CHAT_IMAGE_SEND'
export const SET_CHAT_IMAGE_DATA = 'SET_CHAT_IMAGE_DATA'
export const ON_RECONNECT_CHAT = 'ON_RECONNECT_CHAT'
export const SET_CHAT_INVOICE_VISIBLE = 'SET_CHAT_INVOICE_VISIBLE'
export const SET_CHAT_INVOICE_DATA = 'SET_CHAT_INVOICE_DATA'
export const SET_ATTACHMENT_DATA = 'SET_ATTACHMENT_DATA'
export const ON_SEND_ATTACHMENT = 'ON_SEND_ATTACHMENT'
export const ON_SEND_RECORDING = 'ON_SEND_RECORDING'
export const SET_CHAT_WALLET_ALERT = 'SET_CHAT_WALLET_ALERT'


//Live 
export const SET_LIVE_ID = 'SET_LIVE_ID';;
export const CREATE_LIVE_PROFILE = 'CREATE_LIVE_PROFILE';
export const ADD_LIVE_LISTENER = 'ADD_LIVE_LISTENER';
export const SEND_COMMENTS = 'SEND_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SET_GIFT_DATA = 'SET_GIFT_DATA';
export const SET_GIFT_VISIBLE = 'SET_GIFT_VISIBLE';
export const GET_GIFT_DATA = 'GET_GIFT_DATA';
export const SEND_GIFT_TO_ASTROLOGER = 'SEND_GIFT_TO_ASTROLOGER';
export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';
export const SET_HEARTS = 'SET_HEARTS';
export const SET_EXIT_ALERT_VISIBLE = 'SET_EXIT_ALERT_VISIBLE';
export const SET_IS_LIVE_START = 'SET_IS_LIVE_START';
export const SET_ROOM_USER_COUNT = 'SET_ROOM_USER_COUNT';
export const SET_LIVE_CALLS_VISIBLE = 'SET_LIVE_CALLS_VISIBLE';
export const SET_WAITING_LIST_VISIBLE = 'SET_WAITING_LIST_VISIBLE';
export const ADD_IN_WAITING_LIST = 'ADD_IN_WAITING_LIST';
export const SET_WAITLIST_DATA = 'SET_WAITLIST_DATA';
export const SET_CO_HOST_REQUEST_VISIBLE = 'SET_CO_HOST_REQUEST_VISIBLE';
export const SET_IS_CO_HOST = 'SET_IS_CO_HOST';
export const SET_STREAMING_ID = 'SET_STREAMING_ID';
export const ON_GO_LIVE = 'ON_GO_LIVE';
export const SET_LAYOUT = 'SET_LAYOUT';
export const RESET_LIVE_STATE = 'RESET_LIVE_STATE';
export const SET_CO_HOST_DATA = 'SET_CO_HOST_DATA';
export const ON_END_CALLING = 'ON_END_CALLING';
export const SET_GIFTED_DATA = 'SET_GIFTED_DATA';
export const ON_CANCEL_CALL_REQUEST = 'ON_CANCEL_CALL_REQUEST'
export const SET_LIVE_ASTRO_DATA = 'SET_LIVE_ASTRO_DATA'
export const SET_LIVE_DATA = 'SET_LIVE_DATA'
export const ADD_HEART_BY_OTHERS = 'ADD_HEART_BY_OTHERS'
export const ON_STREAM_UPDATE = 'ON_STREAM_UPDATE'
export const SET_CALL_INFO_VISIBLE = 'SET_CALL_INFO_VISIBLE'
export const GET_LIVE_INVOICE_DATA = 'GET_LIVE_INVOICE_DATA'
export const SET_LIVE_INVOICE_DATA = 'SET_LIVE_INVOICE_DATA'
export const ON_LIVE_MUTE_UNMUTE = 'ON_LIVE_MUTE_UNMUTE'
export const SET_LIVE_IS_MUTE = 'SET_LIVE_IS_MUTE'
export const ON_APP_STATE_CHANGE_IN_LIVE = 'ON_APP_STATE_CHANGE_IN_LIVE'

//History
export const GET_WALLET_HISTORY = 'GET_WALLET_HISTORY'
export const SET_WALLET_HISTORY = 'SET_WALLET_HISTORY'
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY'
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY'
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY'
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY'
export const GET_PRODUCT_HISTORY = "GET_PRODUCT_HISTORY"

//Kundli
export const GET_KUNDLI_DATA = 'GET_KUNDLI_DATA'
export const SET_KUNDLI_DATA = 'SET_KUNDLI_DATA'

//Banners
export const SET_HOME_TOP_BANNER = 'SET_HOME_TOP_BANNER'

