// Settings
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRECING = 'SET_IS_REFRECING';
export const GET_SPLASH = 'GET_SPLASH';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_TAB_VISIBLE = 'SET_TAB_VISIBLE';
export const SET_WALLET_ALERT_VISIBLE = 'SET_WALLET_ALERT_VISIBLE';

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_FACEBOOK_LOGIN = 'ON_FACEBOOK_LOGIN'
export const ON_GOOGLE_LOGIN = 'ON_GOOGLE_LOGIN'
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION'
export const ON_CUSTOMER_REGISTRATION = 'ON_CUSTOMER_REGISTRATION'

//Payments
export const ON_WALLET_RECHARGE = 'ON_WALLET_RECHARGE'

//Customer
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';

//Astrologer
export const GET_CHAT_CALL_ASTROLOGER_LIST = 'GET_CHAT_CALL_ASTROLOGER_LIST';
export const SET_CHAT_ASTROLOGER_LIST = 'SET_CHAT_ASTROLOGER_LIST';
export const SET_CALL_ASTROLOGER_LIST = 'SET_CALL_ASTROLOGER_LIST';
export const GET_ASTROLOGER_DETAILS = 'GET_ASTROLOGER_DETAILS';
export const SET_ASTROLOGER_DETAILS = 'SET_ASTROLOGER_DETAILS';
export const SET_CHAT_REQUEST_MODAL_DATA = 'SET_CHAT_REQUEST_MODAL_DATA';

//Call
export const SEND_CALL_REQUEST = 'SEND_CALL_REQUEST';

//Chat
export const SEND_CHAT_REQUEST = 'SEND_CHAT_REQUEST';
export const START_CHAT = 'START_CHAT';
export const SET_CHAT_DATA = 'SET_CHAT_DATA';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES'
export const SET_CHAT_TIMER_COUNTDOWN = 'SET_CHAT_TIMER_COUNTDOWN'
export const SET_CHAT_REQUESTED_DATA = 'SET_CHAT_REQUESTED_DATA'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE'
export const ON_END_CHAT = 'ON_END_CHAT'
export const ON_CLOSE_CHAT = 'ON_CLOSE_CHAT'
export const ON_CHAT_IMAGE_SEND = 'ON_CHAT_IMAGE_SEND'
export const SET_CHAT_IMAGE_DATA = 'SET_CHAT_IMAGE_DATA'
export const ON_RECONNECT_CHAT = 'ON_RECONNECT_CHAT'
export const SET_CHAT_INVOICE_VISIBLE = 'SET_CHAT_INVOICE_VISIBLE'
export const SET_CHAT_INVOICE_DATA = 'SET_CHAT_INVOICE_DATA'
