// Settings
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRECING = 'SET_IS_REFRECING';
export const GET_SPLASH = 'GET_SPLASH';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_TAB_VISIBLE = 'SET_TAB_VISIBLE';

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_FACEBOOK_LOGIN = 'ON_FACEBOOK_LOGIN'
export const ON_GOOGLE_LOGIN = 'ON_GOOGLE_LOGIN'
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION'
export const ON_CUSTOMER_REGISTRATION = 'ON_CUSTOMER_REGISTRATION'

//Customer
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';

//Astrologer
export const GET_CHAT_CALL_ASTROLOGER_LIST = 'GET_CHAT_CALL_ASTROLOGER_LIST';
export const SET_CHAT_ASTROLOGER_LIST = 'SET_CHAT_ASTROLOGER_LIST';
export const SET_CALL_ASTROLOGER_LIST = 'SET_CALL_ASTROLOGER_LIST';
export const GET_ASTROLOGER_DETAILS = 'GET_ASTROLOGER_DETAILS';
export const SET_ASTROLOGER_DETAILS = 'SET_ASTROLOGER_DETAILS';

//Call
export const SEND_CALL_REQUEST = 'SEND_CALL_REQUEST';

//E-Commerce
export const GET_POOJA_CATEGORY_DATA = "GET_POOJA_CATEGORY_DATA"
export const GET_PRODUCT_CATEGORY_DATA = "GET_PRODUCT_CATEGORY_DATA"
export const GET_CATEGORY_WAISE_PRODUCT_DATA = "GET_CATEGORY_WAISE_PRODUCT_DATA"
export const GET_CATEGORY_WAISE_POOJA_DATA = "GET_CATEGORY_WAISE_POOJA_DATA"

// Course
export const GET_COURSE_BANNER = "GET_COURSE_BANNER"
